# sample
tasks:
  bundle:
    steps:
      - run: bundle install
    tags: ['http']
  yarn:
    steps:
      - run: yarn install
  rails:
    tags: ['http']
    depends:
      - bundle
    steps:
      - run: bin/rails s
  dev-server:
    depends:
      - yarn
    steps:
      - run: yarn start
