# sample
tasks:
  install:
    steps:
      - run: echo installing...; sleep 5; echo done
  server:
    depends:
      - install
    steps:
      - run: while true; do echo serving html; sleep 1s; done
    tags: ['http']
  grpc-server:
    depends:
      - install
    steps:
      - run: while true; do echo serving grpc; sleep 1s; done
    tags: ['grpc']
    env:
      GRPC: 'true'
